logging.level.com.sushi.userprofile.service=DEBUG
logging.level.org.springframework.jdbc.core=DEBUG

spring.data.redis.host=localhost
spring.data.redis.port=6379

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/user_profile_db
spring.datasource.username=sushi
spring.datasource.password=123456

# JDBC
spring.datasource.driver-class-name=org.postgresql.Driver